# 1-  Objetivo

O objetivo dessa análise é buscar instituições privadas que podem tem um potencial 
alto para oferecemos os nosso produtos e dessa forma agregar valor a instutição.

Os dados que estou trabalhando são informações reais retiradas do site do INEP.
O dataset contém inumeras colunas, porém selecionei apenas 30 colunas que etão alinhadas com o que
desejo extrair desses dados.

As mais significativas são as que contém informações que seja possuim localizada 
a instuição , por meio de endereço fisico ou digital. Além disse possui outras informações relevantes
como a existência de biliotecas, equipamento de multimidia, computadores para os alunos , situação atual da instituições,
dentre outras.


###Dicionário dos dados 

NU_ANO_CENSO	- Ano do Censo
NO_REGIAO -	Nome da Região Geográfica
NO_UF -	Nome da Unidade da Federação
SG_UF -	Sigla da Unidade da Federação
NO_MUNICIPIO -	Nome do Município
NO_MICRORREGIAO -	Nome da Microrregião
TP_DEPENDENCIA -	Dependência Administrativa
TP_CATEGORIA_ESCOLA_PRIVADA -	Categoria da escola privada
TP_LOCALIZACAO -	Localização
DS_ENDERECO -	Endereço
NU_ENDERECO -	Número
DS_COMPLEMENTO -	Complemento
NO_BAIRRO -	Bairro
CO_CEP -	CEP
NU_DDD -	DDD
NU_TELEFONE -	Telefone
TP_SITUACAO_FUNCIONAMENTO -	Situação de funcionamento
DT_ANO_LETIVO_INICIO -	Início do ano letivo
DT_ANO_LETIVO_TERMINO -	Término (previsão) do ano letivo
NU_CNPJ_ESCOLA_PRIVADA -	Número do CNPJ da escola privada
TP_REGULAMENTACAO -	Regulamentação/Autorização no conselho ou órgão municipal, estadual ou federal de educação
TP_RESPONSAVEL_REGULAMENTACAO -	Esfera administrativa do conselho ou órgão responsável pela Regulamentação/Autorização
IN_LOCAL_FUNC_PREDIO_ESCOLAR -	Local de funcionamento da escola - Prédio Escolar
TP_OCUPACAO_PREDIO_ESCOLAR -	Forma de ocupação do Prédio escolar
IN_BIBLIOTECA	Dependências - físicas existentes e utilizadas na escola - Biblioteca
IN_LABORATORIO_CIENCIAS -	Dependências físicas existentes e utilizadas na escola - Laboratório de ciências
IN_LABORATORIO_INFORMATICA -	Dependências físicas existentes e utilizadas na escola - Laboratório de informática
IN_EQUIP_MULTIMIDIA -	Equipamentos existentes na escola para o processo ensino e aprendizagem - Projetor Multimídia (Datashow)
IN_DESKTOP_ALUNO -	Computadores em uso pelos alunos - Computador de mesa (desktop)
IN_COMP_PORTATIL_ALUNO -	Computadores em uso pelos alunos - Computador portátil

In [79]:
#importando as bibliotecas
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#Instância os datasets
path_ed_basica_2024 = r'C:\Users\Arthur Lopes\Documents\PROJETO-LVI\microdados_censo_escolar_2024\dados\microdados_ed_basica_2024.csv'

path_suplemento_tecnico = r'C:\Users\Arthur Lopes\Documents\PROJETO-LVI\microdados_censo_escolar_2024\dados\suplemento_cursos_tecnicos_2024.csv'

In [ ]:
#Transfonrmando as planilhas em dataframe
df_ed_basica = pd.read_csv(path_ed_basica_2024, sep=';', encoding='iso-8859-1')

#Exibindo o dataframe
df_ed_basica.head()

C:\Users\Arthur Lopes\AppData\Local\Temp\ipykernel_15544\1477959015.py:3: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ed_basica = pd.read_csv(path_ed_basica_2024, sep=';', encoding='iso-8859-1')

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,...,QT_TUR_BAS_D,QT_TUR_BAS_N,QT_TUR_BAS_EAD,QT_TUR_INF_INT,QT_TUR_INF_CRE_INT,QT_TUR_INF_PRE_INT,QT_TUR_FUND_INT,QT_TUR_FUND_AI_INT,QT_TUR_FUND_AF_INT,QT_TUR_MED_INT
0,2024,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2024,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,...,35.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Transformando o csv em dataframe e utilizando a codicação universal
df_suplemento_tecnico = pd.read_csv(path_suplemento_tecnico,sep=';', encoding='iso-8859-1')

df_suplemento_tecnico.head()

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,TP_LOCALIZACAO,TP_LOCALIZACAO_DIFERENCIADA,...,QT_CURSO_TEC_CT,QT_MAT_CURSO_TEC_CT,QT_CURSO_TEC_NM,QT_MAT_CURSO_TEC_NM,QT_CURSO_TEC_CONC,QT_MAT_CURSO_TEC_CONC,QT_CURSO_TEC_SUBS,QT_MAT_TEC_SUBS,QT_CURSO_TEC_EJA,QT_MAT_TEC_EJA
0,2024,Norte,1,Rondônia,RO,11,Ariquemes,1100023,1,0,...,0,0,0,0,1,10,1,35,0,0
1,2024,Norte,1,Rondônia,RO,11,Ariquemes,1100023,1,0,...,0,0,0,0,1,13,1,36,0,0
2,2024,Norte,1,Rondônia,RO,11,Ariquemes,1100023,1,0,...,0,0,0,0,1,6,1,12,0,0
3,2024,Norte,1,Rondônia,RO,11,Ariquemes,1100023,1,0,...,0,0,0,0,1,14,1,13,0,0
4,2024,Norte,1,Rondônia,RO,11,Ariquemes,1100023,1,0,...,0,0,0,0,1,6,1,39,0,0

In [ ]:
#Dimensão do dataframe educação basica
df_ed_basica.shape

(215545, 426)

#Colunas selecionada para a Analise da base - educação básica

NU_ANO_CENSO
NO_REGIAO
NO_UF
SG_UF
NO_MUNICIPIO
NO_MICRORREGIAO
TP_DEPENDENCIA
TP_CATEGORIA_ESCOLA_PRIVADA
TP_LOCALIZACAO
DS_ENDERECO
NU_ENDERECO
DS_COMPLEMENTO
NO_BAIRRO
CO_CEP
NU_DDD
NU_TELEFONE
TP_SITUACAO_FUNCIONAMENTO
DT_ANO_LETIVO_INICIO
DT_ANO_LETIVO_TERMINO
NU_CNPJ_ESCOLA_PRIVADA
TP_REGULAMENTACAO
TP_RESPONSAVEL_REGULAMENTACAO
IN_LOCAL_FUNC_PREDIO_ESCOLAR
TP_OCUPACAO_PREDIO_ESCOLAR
IN_BIBLIOTECA
IN_LABORATORIO_CIENCIAS
IN_LABORATORIO_INFORMATICA
IN_EQUIP_MULTIMIDIA
IN_DESKTOP_ALUNO
IN_COMP_PORTATIL_ALUNO

In [27]:
#Instânciando dataframe com as colunas especificas
df_ed_basica_01 =  df_ed_basica[['NU_ANO_CENSO','NO_REGIAO','NO_UF','SG_UF','NO_MUNICIPIO','NO_MICRORREGIAO','TP_DEPENDENCIA',
              'TP_CATEGORIA_ESCOLA_PRIVADA','TP_LOCALIZACAO',"DS_ENDERECO",'NU_ENDERECO','DS_COMPLEMENTO',
              'NO_BAIRRO','CO_CEP','NU_DDD','NU_TELEFONE','TP_SITUACAO_FUNCIONAMENTO','DT_ANO_LETIVO_INICIO',
              'DT_ANO_LETIVO_TERMINO','NU_CNPJ_ESCOLA_PRIVADA','TP_REGULAMENTACAO','TP_RESPONSAVEL_REGULAMENTACAO',
              'IN_LOCAL_FUNC_PREDIO_ESCOLAR','TP_OCUPACAO_PREDIO_ESCOLAR','IN_BIBLIOTECA','IN_LABORATORIO_CIENCIAS',
              'IN_LABORATORIO_INFORMATICA','IN_EQUIP_MULTIMIDIA','IN_DESKTOP_ALUNO','IN_COMP_PORTATIL_ALUNO']]

#Exibindo o dataframe
df_ed_basica_01.head()

,NU_ANO_CENSO,NO_REGIAO,NO_UF,SG_UF,NO_MUNICIPIO,NO_MICRORREGIAO,TP_DEPENDENCIA,TP_CATEGORIA_ESCOLA_PRIVADA,TP_LOCALIZACAO,DS_ENDERECO,...,TP_REGULAMENTACAO,TP_RESPONSAVEL_REGULAMENTACAO,IN_LOCAL_FUNC_PREDIO_ESCOLAR,TP_OCUPACAO_PREDIO_ESCOLAR,IN_BIBLIOTECA,IN_LABORATORIO_CIENCIAS,IN_LABORATORIO_INFORMATICA,IN_EQUIP_MULTIMIDIA,IN_DESKTOP_ALUNO,IN_COMP_PORTATIL_ALUNO
0,2024,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,2,NaN,2,TERRA INDIGENA RIO BRANCO,...,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2024,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,2,NaN,1,AVENIDA RIO DE JANEIRO,...,1.0,2.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
2,2024,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,3,NaN,2,LINHA 60 COM A 140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,3,NaN,2,LINHA P 50 KM 22,...,1.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2024,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,2,NaN,1,AVENIDA MATO GROSSO,...,1.0,2.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0

In [29]:
#Exibindo as colunas
df_ed_basica_01.columns

Index(['NU_ANO_CENSO', 'NO_REGIAO', 'NO_UF', 'SG_UF', 'NO_MUNICIPIO',
       'NO_MICRORREGIAO', 'TP_DEPENDENCIA', 'TP_CATEGORIA_ESCOLA_PRIVADA',
       'TP_LOCALIZACAO', 'DS_ENDERECO', 'NU_ENDERECO', 'DS_COMPLEMENTO',
       'NO_BAIRRO', 'CO_CEP', 'NU_DDD', 'NU_TELEFONE',
       'TP_SITUACAO_FUNCIONAMENTO', 'DT_ANO_LETIVO_INICIO',
       'DT_ANO_LETIVO_TERMINO', 'NU_CNPJ_ESCOLA_PRIVADA', 'TP_REGULAMENTACAO',
       'TP_RESPONSAVEL_REGULAMENTACAO', 'IN_LOCAL_FUNC_PREDIO_ESCOLAR',
       'TP_OCUPACAO_PREDIO_ESCOLAR', 'IN_BIBLIOTECA',
       'IN_LABORATORIO_CIENCIAS', 'IN_LABORATORIO_INFORMATICA',
       'IN_EQUIP_MULTIMIDIA', 'IN_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO'],
      dtype='object')

# 2 -Tratamento dos dados

In [32]:
#Verificando as colunas que possui nulos

df_ed_basica_01.isnull().sum()

NU_ANO_CENSO                          0
NO_REGIAO                             0
NO_UF                                 0
SG_UF                                 0
NO_MUNICIPIO                          0
NO_MICRORREGIAO                       0
TP_DEPENDENCIA                        0
TP_CATEGORIA_ESCOLA_PRIVADA      172327
TP_LOCALIZACAO                        0
DS_ENDERECO                           1
NU_ENDERECO                       41924
DS_COMPLEMENTO                   144577
NO_BAIRRO                         28640
CO_CEP                                0
NU_DDD                            32088
NU_TELEFONE                       43418
TP_SITUACAO_FUNCIONAMENTO             0
DT_ANO_LETIVO_INICIO              34480
DT_ANO_LETIVO_TERMINO             34480
NU_CNPJ_ESCOLA_PRIVADA           172327
TP_REGULAMENTACAO                 34480
TP_RESPONSAVEL_REGULAMENTACAO     39098
IN_LOCAL_FUNC_PREDIO_ESCOLAR      34480
TP_OCUPACAO_PREDIO_ESCOLAR        38281
IN_BIBLIOTECA                     34480
IN_LABORATORIO_CIENCIAS           34480
IN_LABORATORIO_INFORMATICA        34480
IN_EQUIP_MULTIMIDIA               34480
IN_DESKTOP_ALUNO                  34480
IN_COMP_PORTATIL_ALUNO            34480
dtype: int64

In [ ]:
#Verificando o tipo de cada atributo
df_ed_basica_01.dtypes

NU_ANO_CENSO                       int64
NO_REGIAO                         object
NO_UF                             object
SG_UF                             object
NO_MUNICIPIO                      object
NO_MICRORREGIAO                   object
TP_DEPENDENCIA                     int64
TP_CATEGORIA_ESCOLA_PRIVADA      float64
TP_LOCALIZACAO                     int64
DS_ENDERECO                       object
NU_ENDERECO                       object
DS_COMPLEMENTO                    object
NO_BAIRRO                         object
CO_CEP                             int64
NU_DDD                           float64
NU_TELEFONE                      float64
TP_SITUACAO_FUNCIONAMENTO          int64
DT_ANO_LETIVO_INICIO              object
DT_ANO_LETIVO_TERMINO             object
NU_CNPJ_ESCOLA_PRIVADA           float64
TP_REGULAMENTACAO                float64
TP_RESPONSAVEL_REGULAMENTACAO    float64
IN_LOCAL_FUNC_PREDIO_ESCOLAR     float64
TP_OCUPACAO_PREDIO_ESCOLAR       float64
IN_BIBLIOTECA                    float64
IN_LABORATORIO_CIENCIAS          float64
IN_LABORATORIO_INFORMATICA       float64
IN_EQUIP_MULTIMIDIA              float64
IN_DESKTOP_ALUNO                 float64
IN_COMP_PORTATIL_ALUNO           float64
dtype: object

 O atributo TP_DEPENDENCIA informa se a escola é publica ou particular
e o objetivo é obter dados somente das instituições particulares.
Esse atributo está categorizado como:

1- Federal
2- Estadual
3- Municipal
4- Privada

In [51]:
df_ed_basica_01["TP_DEPENDENCIA"].unique()

array([2, 4, 3, 1])

In [53]:
#Selecionando os dados do atribuido TP_DEPENDENCIA seja igual a 4
df_ed_basica_02 = df_ed_basica_01.loc[df_ed_basica_01["TP_DEPENDENCIA"] == 4]

#Exibindo o dataframe
df_ed_basica_02.head()

,NU_ANO_CENSO,NO_REGIAO,NO_UF,SG_UF,NO_MUNICIPIO,NO_MICRORREGIAO,TP_DEPENDENCIA,TP_CATEGORIA_ESCOLA_PRIVADA,TP_LOCALIZACAO,DS_ENDERECO,...,TP_REGULAMENTACAO,TP_RESPONSAVEL_REGULAMENTACAO,IN_LOCAL_FUNC_PREDIO_ESCOLAR,TP_OCUPACAO_PREDIO_ESCOLAR,IN_BIBLIOTECA,IN_LABORATORIO_CIENCIAS,IN_LABORATORIO_INFORMATICA,IN_EQUIP_MULTIMIDIA,IN_DESKTOP_ALUNO,IN_COMP_PORTATIL_ALUNO
1,4,4,4,4,4,4,4,4.0,4,4,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
2,4,4,4,4,4,4,4,4.0,4,4,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
3,4,4,4,4,4,4,4,4.0,4,4,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
4,4,4,4,4,4,4,4,4.0,4,4,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
22,2024,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,4,4.0,1,AV MINAS GERAIS ESQUINA COM A FORTALEZA,...,2.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0

In [ ]:
#Verificando a dimensão 
df_ed_basica_02.shape

(52572, 30)

In [55]:
df_ed_basica_02.isnull().sum()

NU_ANO_CENSO                         0
NO_REGIAO                            0
NO_UF                                0
SG_UF                                0
NO_MUNICIPIO                         0
NO_MICRORREGIAO                      0
TP_DEPENDENCIA                       0
TP_CATEGORIA_ESCOLA_PRIVADA       9350
TP_LOCALIZACAO                       0
DS_ENDERECO                          0
NU_ENDERECO                       3442
DS_COMPLEMENTO                   36536
NO_BAIRRO                          834
CO_CEP                               0
NU_DDD                            4302
NU_TELEFONE                       5325
TP_SITUACAO_FUNCIONAMENTO            0
DT_ANO_LETIVO_INICIO              9350
DT_ANO_LETIVO_TERMINO             9350
NU_CNPJ_ESCOLA_PRIVADA            9350
TP_REGULAMENTACAO                 9350
TP_RESPONSAVEL_REGULAMENTACAO    10140
IN_LOCAL_FUNC_PREDIO_ESCOLAR      9350
TP_OCUPACAO_PREDIO_ESCOLAR       10461
IN_BIBLIOTECA                     9350
IN_LABORATORIO_CIENCIAS           9350
IN_LABORATORIO_INFORMATICA        9350
IN_EQUIP_MULTIMIDIA               9350
IN_DESKTOP_ALUNO                  9350
IN_COMP_PORTATIL_ALUNO            9350
dtype: int64

O Atributo 'TP_SITUACAO_FUNCIONAMENTO' informa a situação da instituição
como :

 1 - Em atividade 
2 - Paralisada
3 - Extinta ( 2024)
4 - Exinta nos anos anteriores

In [57]:
#Selecionando somente as instituições em atividade
df_ed_basica_03 = df_ed_basica_02.loc[df_ed_basica_01["TP_SITUACAO_FUNCIONAMENTO"] == 1]

#exibindo o dataframe
df_ed_basica_03.head()

,NU_ANO_CENSO,NO_REGIAO,NO_UF,SG_UF,NO_MUNICIPIO,NO_MICRORREGIAO,TP_DEPENDENCIA,TP_CATEGORIA_ESCOLA_PRIVADA,TP_LOCALIZACAO,DS_ENDERECO,...,TP_REGULAMENTACAO,TP_RESPONSAVEL_REGULAMENTACAO,IN_LOCAL_FUNC_PREDIO_ESCOLAR,TP_OCUPACAO_PREDIO_ESCOLAR,IN_BIBLIOTECA,IN_LABORATORIO_CIENCIAS,IN_LABORATORIO_INFORMATICA,IN_EQUIP_MULTIMIDIA,IN_DESKTOP_ALUNO,IN_COMP_PORTATIL_ALUNO
22,2024,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,4,4.0,1,AV MINAS GERAIS ESQUINA COM A FORTALEZA,...,2.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
32,2024,Norte,Rondônia,RO,Ariquemes,Ariquemes,4,4.0,1,AVENIDA TABAPUA,...,1.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
34,2024,Norte,Rondônia,RO,Ariquemes,Ariquemes,4,4.0,1,RUA SALVADOR,...,1.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
40,2024,Norte,Rondônia,RO,Ariquemes,Ariquemes,4,4.0,1,RUA GOIAS,...,1.0,3.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
53,2024,Norte,Rondônia,RO,Ariquemes,Ariquemes,4,1.0,1,RUA FORTALEZA,...,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [58]:
#Validando a categoria existente no atributo 
df_ed_basica_03["TP_SITUACAO_FUNCIONAMENTO"].unique()

array([1])

In [59]:
#analisando a distruição
df_ed_basica_03.shape

(43218, 30)

In [60]:
df_ed_basica_03.isnull().sum()

NU_ANO_CENSO                         0
NO_REGIAO                            0
NO_UF                                0
SG_UF                                0
NO_MUNICIPIO                         0
NO_MICRORREGIAO                      0
TP_DEPENDENCIA                       0
TP_CATEGORIA_ESCOLA_PRIVADA          0
TP_LOCALIZACAO                       0
DS_ENDERECO                          0
NU_ENDERECO                       1572
DS_COMPLEMENTO                   28789
NO_BAIRRO                          252
CO_CEP                               0
NU_DDD                            1864
NU_TELEFONE                       2711
TP_SITUACAO_FUNCIONAMENTO            0
DT_ANO_LETIVO_INICIO                 0
DT_ANO_LETIVO_TERMINO                0
NU_CNPJ_ESCOLA_PRIVADA               0
TP_REGULAMENTACAO                    0
TP_RESPONSAVEL_REGULAMENTACAO      790
IN_LOCAL_FUNC_PREDIO_ESCOLAR         0
TP_OCUPACAO_PREDIO_ESCOLAR        1111
IN_BIBLIOTECA                        0
IN_LABORATORIO_CIENCIAS              0
IN_LABORATORIO_INFORMATICA           0
IN_EQUIP_MULTIMIDIA                  0
IN_DESKTOP_ALUNO                     0
IN_COMP_PORTATIL_ALUNO               0
dtype: int64

In [63]:
#Verificando o ano

df_ed_basica_03["NU_ANO_CENSO"].unique()

array([2024])

In [ ]:
#Os estados que contém o dataset
df_ed_basica_03["NO_UF"].unique()

array(['Rondônia', 'Acre', 'Amazonas', 'Roraima', 'Pará', 'Amapá',
       'Tocantins', 'Maranhão', 'Piauí', 'Ceará', 'Rio Grande do Norte',
       'Paraíba', 'Pernambuco', 'Alagoas', 'Sergipe', 'Bahia',
       'Minas Gerais', 'Espírito Santo', 'Rio de Janeiro', 'São Paulo',
       'Paraná', 'Santa Catarina', 'Rio Grande do Sul',
       'Mato Grosso do Sul', 'Mato Grosso', 'Goiás', 'Distrito Federal'],
      dtype=object)

In [66]:
df_ed_basica_03["NO_REGIAO"].unique()

array(['Norte', 'Nordeste', 'Sudeste', 'Sul', 'Centro-Oeste'],
      dtype=object)

In [69]:
df_ed_basica_03["SG_UF"].unique()

array(['RO', 'AC', 'AM', 'RR', 'PA', 'AP', 'TO', 'MA', 'PI', 'CE', 'RN',
       'PB', 'PE', 'AL', 'SE', 'BA', 'MG', 'ES', 'RJ', 'SP', 'PR', 'SC',
       'RS', 'MS', 'MT', 'GO', 'DF'], dtype=object)

In [75]:
df_ed_basica_03.columns

Index(['NU_ANO_CENSO', 'NO_REGIAO', 'NO_UF', 'SG_UF', 'NO_MUNICIPIO',
       'NO_MICRORREGIAO', 'TP_DEPENDENCIA', 'TP_CATEGORIA_ESCOLA_PRIVADA',
       'TP_LOCALIZACAO', 'DS_ENDERECO', 'NU_ENDERECO', 'DS_COMPLEMENTO',
       'NO_BAIRRO', 'CO_CEP', 'NU_DDD', 'NU_TELEFONE',
       'TP_SITUACAO_FUNCIONAMENTO', 'DT_ANO_LETIVO_INICIO',
       'DT_ANO_LETIVO_TERMINO', 'NU_CNPJ_ESCOLA_PRIVADA', 'TP_REGULAMENTACAO',
       'TP_RESPONSAVEL_REGULAMENTACAO', 'IN_LOCAL_FUNC_PREDIO_ESCOLAR',
       'TP_OCUPACAO_PREDIO_ESCOLAR', 'IN_BIBLIOTECA',
       'IN_LABORATORIO_CIENCIAS', 'IN_LABORATORIO_INFORMATICA',
       'IN_EQUIP_MULTIMIDIA', 'IN_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO'],
      dtype='object')

Nessa etapa será realizada a padronização dos atributos. 
As colunas que são string ficarão com letras maiusculas

In [80]:
#Verificando o tipo
#df_ed_basica_03.dtypes

df_ed_basica_03["NO_REGIAO"] = df_ed_basica_03["NO_REGIAO"].str.upper()

df_ed_basica_03['NO_UF'] = df_ed_basica_03['NO_UF'].str.upper()

df_ed_basica_03['SG_UF'] = df_ed_basica_03['SG_UF'].str.upper()

df_ed_basica_03['NO_MUNICIPIO'] = df_ed_basica_03['NO_MUNICIPIO'].str.upper()

df_ed_basica_03["DS_ENDERECO"] = df_ed_basica_03["DS_ENDERECO"].str.upper()

df_ed_basica_03["DS_COMPLEMENTO"] = df_ed_basica_03["DS_COMPLEMENTO"].str.upper()

df_ed_basica_03["NO_BAIRRO"] = df_ed_basica_03["NO_BAIRRO"].str.upper()

df_ed_basica_03["NO_MICRORREGIAO"] = df_ed_basica_03["NO_MICRORREGIAO"].str.upper()

#Exibindo o dataframe
df_ed_basica_03.head()

,NU_ANO_CENSO,NO_REGIAO,NO_UF,SG_UF,NO_MUNICIPIO,NO_MICRORREGIAO,TP_DEPENDENCIA,TP_CATEGORIA_ESCOLA_PRIVADA,TP_LOCALIZACAO,DS_ENDERECO,...,TP_REGULAMENTACAO,TP_RESPONSAVEL_REGULAMENTACAO,IN_LOCAL_FUNC_PREDIO_ESCOLAR,TP_OCUPACAO_PREDIO_ESCOLAR,IN_BIBLIOTECA,IN_LABORATORIO_CIENCIAS,IN_LABORATORIO_INFORMATICA,IN_EQUIP_MULTIMIDIA,IN_DESKTOP_ALUNO,IN_COMP_PORTATIL_ALUNO
22,2024,NORTE,RONDÔNIA,RO,ALTA FLORESTA D'OESTE,CACOAL,4,4.0,1,AV MINAS GERAIS ESQUINA COM A FORTALEZA,...,2.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
32,2024,NORTE,RONDÔNIA,RO,ARIQUEMES,ARIQUEMES,4,4.0,1,AVENIDA TABAPUA,...,1.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
34,2024,NORTE,RONDÔNIA,RO,ARIQUEMES,ARIQUEMES,4,4.0,1,RUA SALVADOR,...,1.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
40,2024,NORTE,RONDÔNIA,RO,ARIQUEMES,ARIQUEMES,4,4.0,1,RUA GOIAS,...,1.0,3.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
53,2024,NORTE,RONDÔNIA,RO,ARIQUEMES,ARIQUEMES,4,1.0,1,RUA FORTALEZA,...,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [ ]:
#Exportando para csv

df_ed_basica_03.to_excel("Instituicoes_privadas.xlsx", index=False)